# Generated by Django 4.1.7 on 2023-08-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_assettype_glline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "abbreviation",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
