# Generated by Django 4.1.7 on 2023-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_account_accountentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "charge_type_ID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("short_description", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[("flat", "Flat Charge"), ("percentage", "Percentage")],
                        default="percentage",
                        max_length=100,
                    ),
                ),
                ("value", models.FloatField(default=100)),
                (
                    "Dr_charge_GL_category",
                    models.CharField(default="NA", max_length=100),
                ),
                (
                    "Cr_charge_GL_category",
                    models.CharField(default="NA", max_length=100),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
