# Generated by Django 4.1.7 on 2023-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_chargetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("short_description", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
