# Generated by Django 4.1.7 on 2023-09-03 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="receipt_number",
        ),
    ]
