# Generated by Django 4.1.7 on 2023-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_sale_unit_price_alter_sale_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
